name: Backend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
      - 'feat/**'
      - 'sprint/**'
      - 'bug/**'
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - development
      - 'feat/**'
      - 'sprint/**'
      - 'bug/**'
    paths:
      - 'backend/**'

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          projectBaseDir: ./backend
          extraProperties: |
            sonar.php.coverage.reportPaths=backend/coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
